# -*- coding: utf-8 -*-
"""Day 4 Assignment Millicent

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11YgHAQsdC48_2ja-KXGaN64kBi0kU508
"""

#Number1
x = 10
y = 20
z = 30
print(x+y+z)

#Number2
x = int(input("Enter First value"))
y = int(input("Enter second value"))

if x >= y:
  greatest = x

else:

    greatest = y

print("Greatest Number is", greatest)